version: "3"

services:
  zookeeper:
    container_name: zookeeper_sds
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  postgres:
    container_name: postgres_sds
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "payments"
    ports:
      - "5432:5432"

  kafka:
    container_name: kafka_sds
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,UI:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,UI://:9093	
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,UI://kafka_sds:9093
    depends_on:
      - zookeeper
      
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
